### ISSUE TITLE
Table Improvement

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp-journal-paper#50] opened 2016-06-09 20:10 UTC
- [x] Revisions to tables as needed once we have a working version
- [ ] Initial version of table 3, capturing core information at a summary level 

@MrAE @alexbaden

**Comment by alexbaden** [comment] 2016-06-10 18:11
What is table 3?

**Comment by jovo** [comment] 2016-06-12 06:57
@willgray i also don't have clarity on what is in table 3, so it doesn't feel like a top priority.  can you provide a DoD for table 3?  in the meantime:

### both tables (and all future tables)
- [x] captions go _above_ the table, not below.

### table 1
- [x] add clarity, kristina @alexbaden 
- [x] add # time steps to #data/#ch 
- [x] i don't love the 2 rows, maybe just use GV & Depth, and we can explain in the captions?

### table 2
- [x] references are not correct, they are image tokens or something.  let's use references to connect it with table 1.
- [x] can we easily get an approx # of RAMON objects? @alexbaden
- [x] add CLARITY @alexbaden

**Comment by alexbaden** [comment] 2016-06-12 20:54
I tagged myself with the issues I am working. @MrAE let me know if you need # timesteps again.

As far as the RAMON objects goes, we only have RAMON counts for two entries in Table 2 -- xbrain and kasthuri. The rest of the datasets are not RAMONified and it's super difficult to count the number of object IDs without having RAMON data. We might be able to RAMONify as a revision task, but I think that will be a month or so of work.

**Comment by jovo** [comment] 2016-06-12 21:11
ok, for # objects, for those we have RAMON, let's put in the exact number.

for those not, let's put in O(10), O(100), etc., which is our guess.
we can refine at revision, but it even kind of makes our point about
RAMON...

On Sun, Jun 12, 2016 at 10:54 PM, Alex Baden notifications@github.com
wrote:

> I tagged myself with the issues I am working. @MrAE
> https://github.com/MrAE let me know if you need # timesteps again.
> 
> As far as the RAMON objects goes, we only have RAMON counts for two
> entries in Table 2 -- xbrain and kasthuri. The rest of the datasets are not
> RAMONified and it's super difficult to count the number of object IDs
> without having RAMON data. We might be able to RAMONify as a revision task,
> but I think that will be a month or so of work.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/50#issuecomment-225459737,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcgbjGIhhxiwXPyHkuHreFFv1zm8nks5qLHICgaJpZM4IyWzQ
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by alexbaden** [comment] 2016-06-12 21:12
Ok. I'm not sure how to do this. You, Will, and I might need to huddle.

**Comment by jovo** [comment] 2016-06-12 21:21
i think @willgray should be able to count RAMON objects and give you an
estimate of objects that aren't RAMONified (a top of his head guess, taking
no more than a few minutes), and then we are done with tables 1 & 2!

On Sun, Jun 12, 2016 at 11:12 PM, Alex Baden notifications@github.com
wrote:

> Ok. I'm not sure how to do this. You, Will, and I might need to huddle.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/50#issuecomment-225460738,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcg6drYtNyAwx2gU0QeqroFig79vuks5qLHZOgaJpZM4IyWzQ
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment] 2016-06-13 12:36
i'll work on this counting, probably tomorrow.  @alexbaden @MrAE - work on the rest of this?

**Comment by alexbaden** [comment] 2016-06-13 15:59
I finished my table 1 tasks. The following still needs to be done:
- [x] reference for kristina15 and the clarity data 
- [x] species for kristina15 and clarity

Any ideas?

**Comment by wrgr** [comment] 2016-06-13 16:27
Clarity is mouse.

**Comment by alexbaden** [comment] 2016-06-13 21:34
Seems to be a duplicate of #51 at this point, which I find very confusing. So, I'm going to close this one. @willgray open a new issue for Table 3, if and when that happens?

**Closed as completed by alexbaden** 2016-06-13 21:34 UTC
